name: "AJAZZ AJ139 V2 Pro"
brand: "AJAZZ"
dimensions: "125.4 x 63.3 x 38.2mm"
weight: "66g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
