name: "AJAZZ AJ139P V3 MC"
brand: "AJAZZ"
dimensions: "127.8 x 64.1 x 39.5mm"
weight: "69g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-24000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
