name: "ASUS ROG Harpe Mini Core"
brand: "ASUS"
dimensions: "117 x 63 x 37mm"
weight: "52g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-12000"
pollingRate: "1000Hz"
connection: "Wired"
buttons: "5"
