name: "ATK Y9 Pro Max"
brand: "ATK"
dimensions: "125.6 x 67.5 x 43.3mm"
weight: "55g"
shape: "Ergonomic"
sensor: "PixArt PAW3395 Ultra"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
