name: "ATK GHOST Extreme"
brand: "ATK"
dimensions: "121 x 61.3 x 38mm"
weight: "48g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950 Ultra"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
