name: "ATK A9 Air"
brand: "ATK"
dimensions: "125 x 64 x 40mm"
weight: "47g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950 Ultra"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
