name: "ATK Z1 V2 Ultimate"
brand: "ATK"
dimensions: "122.5 x 66.8 x 42.4mm"
weight: "54g"
shape: "Ergonomic"
sensor: "PixArt PAW3950"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
