name: "ATK F1 V2 Ultra Max"
brand: "ATK"
dimensions: "118.2 x 62.4 x 38.8mm"
weight: "54g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395 Ultra"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
