name: "ATK X1 V2 Ultra Max"
brand: "ATK"
dimensions: "127 x 64 x 40mm"
weight: "55g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395 Ultra"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
