name: "Attack Shark V8"
brand: "Attack Shark"
dimensions: "126.4 x 67.8 x 40.7mm"
weight: "59g"
shape: "Ergonomic"
sensor: "PixArt PAW3950 Max"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
