name: "Attack Shark V3"
brand: "Attack Shark"
dimensions: "127.4 x 70.2 x 42.5mm"
weight: "65g"
shape: "Ergonomic"
sensor: "PixArt PAW3311"
dpiRange: "100-25000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
