name: "Attack Shark V6"
brand: "Attack Shark"
dimensions: "130 x 75 x 43mm"
weight: "65g"
shape: "Ergonomic"
sensor: "PixArt PAW3311"
dpiRange: "100-25000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
