name: "Attack Shark X8 Ultimate"
brand: "Attack Shark"
dimensions: "125.5 x 63 x 40mm"
weight: "55g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950 Max"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
