name: "be quiet! Dark Perk Ergo"
brand: "be quiet!"
dimensions: "120 x 66 x 40mm"
weight: "55g"
shape: "Ergonomic"
sensor: "PixArt PAW3950"
dpiRange: "100-32000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
