name: "be quiet! Dark Perk Sym"
brand: "be quiet!"
dimensions: "123 x 66 x 39mm"
weight: "55g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-32000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
