name: "Cherry MW5500"
brand: "Cherry"
dimensions: "119 x 61 x 38mm"
weight: "62g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
