name: "Chilkey Glacier LW 8K L"
brand: "Chilkey"
dimensions: "120 x 63 x 39mm"
weight: "47g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
