name: "cOoLm0Dz Qt1p"
brand: "cOoLm0Dz"
dimensions: "80.2 x 59.9 x 24.2mm"
weight: "19g"
shape: "Ambidextrous"
sensor: "PixArt PAW3399"
dpiRange: "100-20000"
pollingRate: "8000Hz"
connection: "Wired"
buttons: "3"
