name: "Corsair Ironclaw Wireless SE"
brand: "Corsair"
dimensions: "130 x 80 x 45mm"
weight: "130g"
shape: "Ergonomic"
sensor: "Corsair MARKSMAN 26K"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "6"
