name: "Corsair Ironclaw Wireless SE"
brand: "Corsair"
dimensions: "111.5 x 68.3 x 40.4mm"
weight: "135g"
shape: "Ergonomic"
sensor: "Corsair MARKSMAN 26K"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 6
