name: "CRDRAKO KO-ONE"
brand: "CRDRAKO"
dimensions: "116 x 62 x 37mm"
weight: "35g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
