name: "Cybeart Ghost"
brand: "Cybeart"
dimensions: "130 x 70 x 44mm"
weight: "49g"
shape: "Ambidextrous"
sensor: "Instant A825"
dpiRange: "100-12800"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 5
