name: "Cybeart Artemis"
brand: "Cybeart"
dimensions: "125 x 63 x 38mm"
weight: "52g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-24000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
