name: "Dareu A950 Pro"
brand: "Dareu"
dimensions: "123 x 64 x 39mm"
weight: "55g"
shape: "Ergonomic"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "4000Hz"
connection: "Wireless"
buttons: 5
