name: "Dareu AE7 Pro"
brand: "Dareu"
dimensions: "125.6 x 67.6 x 44.3mm"
weight: "62g"
shape: "Ergonomic"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
