name: "Dareu A950 GM"
brand: "Dareu"
dimensions: "122.9 x 64.1 x 38.8mm"
weight: "60g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
