name: "Razer DeathAdder V3"
brand: "Razer"
weight: "59g"
shape: "Ergonomic (Right)"
dimensions: "128 x 68 x 44mm"
sensor: "Focus Pro 30K"
dpiRange: "100-30000"
pollingRate: "8000Hz"
buttons: 5
connection: "Wired"
