name: "Delux M400"
brand: "Delux"
dimensions: "126.7 x 63.3 x 40mm"
weight: "75g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-24000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
