name: "Dream Machines DM9 Skill Wired"
brand: "Dream Machines"
dimensions: "129 x 66 x 39mm"
weight: "48g"
shape: "Ambidextrous"
sensor: "PixArt PMW3389"
dpiRange: "100-16000"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 5
