name: "ELECOM VM800L"
brand: "ELECOM"
dimensions: "130 x 70 x 43mm"
weight: "64g"
shape: "Ergonomic"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
