name: "Endgame Gear OP1 8K"
brand: "Endgame Gear"
weight: "59g"
shape: "Symmetrical"
dimensions: "122 x 62 x 38mm"
sensor: "PAW3395"
dpiRange: "50-26000"
pollingRate: "8000Hz"
buttons: 5
connection: "Wired"
