name: "Endgame Gear XM2w"
brand: "Endgame Gear"
weight: "63g"
shape: "Symmetrical"
dimensions: "120 x 66 x 38mm"
sensor: "PAW3370"
dpiRange: "50-19000"
pollingRate: "1000Hz"
buttons: 5
connection: "Wireless"
