name: "EWEADN S9 V2 Ultra"
brand: "EWEADN"
dimensions: "127 x 64.8 x 40.5mm"
weight: "60g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
