name: "EWEADN S7 Pro"
brand: "EWEADN"
dimensions: "125.5 x 62.5 x 39.3mm"
weight: "52g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
