name: "EWEADN A7"
brand: "EWEADN"
dimensions: "125.9 x 75 x 42.6mm"
weight: "59g"
shape: "Ergonomic"
sensor: "PixArt PAW3311"
dpiRange: "100-12000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
