name: "Finalmouse ULX Sakura Small"
brand: "Finalmouse"
dimensions: "115.6 x 60 x 35.2mm"
weight: "33g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-6400"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
