name: "Flickshot One Pro Medium LHD"
brand: "Flickshot"
dimensions: "123 x 61 x 38mm"
weight: "35g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
