name: "Flick Edge"
brand: "Flick"
dimensions: "122.9 x 62.3 x 38mm"
weight: "52g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
