name: "Flickshot One Pro Small LHD"
brand: "Flickshot"
dimensions: "117.6 x 57 x 36.6mm"
weight: "35g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
