name: "Flickshot Evora Pro Fingertip"
brand: "Flickshot"
dimensions: "89.8 x 68.4 x 43mm"
weight: "26g"
shape: "Ergonomic"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
