name: "Glorious Model O"
brand: "Glorious"
weight: "67g"
shape: "Ambidextrous"
sensor: "PMW3360"
dpiRange: "400-12000"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 6
affiliateLink: "https://www.amazon.com/dp/B07MGDRBBF?tag=prosettings-20"
