name: "Glorious Model O 2"
brand: "Glorious"
weight: "59g"
shape: "Ambidextrous"
dimensions: "128 x 66 x 37.5mm"
sensor: "BAMF 2.0"
dpiRange: "100-26000"
pollingRate: "4000Hz"
buttons: 6
connection: "Both"
