name: "Glorious Model O3"
brand: "Glorious"
dimensions: "124 x 61.4 x 39.8mm"
weight: "66g"
shape: "Ambidextrous"
sensor: "Glorious BAMF 3.0"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B07MGDRBBF?tag=prosettings-20"
