name: "Hator Pulsar 3 Pro"
brand: "Hator"
dimensions: "123 x 68 x 38mm"
weight: "65g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
