name: "Hator Pulsar 3 Ultra"
brand: "Hator"
dimensions: "123 x 68 x 38mm"
weight: "61g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "4000Hz"
connection: "Wireless"
buttons: 5
