name: "Hator Pulsar 3"
brand: "Hator"
dimensions: "123 x 68 x 38mm"
weight: "62g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-12000"
pollingRate: "1000Hz"
connection: "Wired"
buttons: "5"
