name: "Hator Quasar 3 Wireless"
brand: "Hator"
dimensions: "125 x 64 x 40mm"
weight: "64g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-12000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
