name: "Hitscan Hyperlight"
brand: "Hitscan"
weight: "39g"
shape: "Ambidextrous"
dimensions: "118 x 61 x 38 mm"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
