name: "IROK HE6"
brand: "IROK"
dimensions: "120 x 61.5 x 39.2mm"
weight: "53g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
