name: "JamesDonkey RSR7 Ultra"
brand: "JamesDonkey"
dimensions: "120 x 63 x 38.3mm"
weight: "43g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
