name: "Keychron BM24"
brand: "Keychron"
dimensions: "104 x 63 x 39mm"
weight: "81g"
shape: "Ambidextrous"
sensor: "SOC 3212"
dpiRange: "100-2400"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
