name: "Keychron BM22"
brand: "Keychron"
dimensions: "111 x 62 x 39mm"
weight: "76g"
shape: "Ambidextrous"
sensor: "SOC 3212"
dpiRange: "100-2400"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
