name: "Lamzu Atlantis Mini"
brand: "Lamzu"
weight: "49g"
shape: "Symmetrical"
sensor: "PAW3395"
dpiRange: "50-26000"
pollingRate: "4000Hz"
connection: "Wireless"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B0BQ4FKGB9?tag=prosettings-20"
