name: "Lethal Gaming Gear LA-1"
brand: "Lethal Gaming Gear"
weight: "47g"
shape: "Symmetrical"
dimensions: "120 x 63 x 38mm"
sensor: "PAW3395"
dpiRange: "50-26000"
pollingRate: "1000Hz"
buttons: 5
connection: "Wireless"
