name: "Logitech G502 X Plus"
brand: "Logitech"
weight: "106g"
shape: "Ergonomic"
dimensions: "131 x 79 x 41mm"
sensor: "HERO 25K"
dpiRange: "100-25600"
pollingRate: "1000Hz"
buttons: 13
connection: "Wireless"
