name: "LunaFury LUNA33"
brand: "LunaFury"
dimensions: "119.3 x 63.6 x 37.3mm"
weight: "40g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950 Pro"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
