name: "LunaFury TYPE77"
brand: "LunaFury"
dimensions: "122 x 61 x 36.5mm"
weight: "43.5g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
