name: "MAMBASNAKE M2"
brand: "MAMBASNAKE"
dimensions: "116.2 x 61.6 x 38.4mm"
weight: "41g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395 Pro"
dpiRange: "100-40000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
