name: "MCHOSE A5 V3"
brand: "MCHOSE"
dimensions: "121.6 x 61.5 x 37.7mm"
weight: "56g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
