name: "Mountain Makalu 67"
brand: "Mountain"
weight: "67g"
shape: "Ergonomic"
dimensions: "124 x 67 x 42mm"
sensor: "PAW3370"
dpiRange: "400-19000"
pollingRate: "1000Hz"
buttons: 6
connection: "Wired"
