name: "Orbital Pathfinder AAH-222"
brand: "Orbital"
dimensions: "126 x 63 x 38mm"
weight: "55.2g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
