name: "Orbital Pathfinder PSM-000"
brand: "Orbital"
dimensions: "118 x 64.5 x 38mm"
weight: "54.3g"
shape: "Hybrid"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
