name: "Orbital Pathfinder PSM-222"
brand: "Orbital"
dimensions: "126 x 69.5 x 38mm"
weight: "55.8g"
shape: "Hybrid"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
