name: "Orbital Pathfinder AAH-000"
brand: "Orbital"
dimensions: "118 x 58 x 38mm"
weight: "53.7g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
