name: "Orbital Pathfinder LRR-000"
brand: "Orbital"
dimensions: "121.2 x 62.5 x 38mm"
weight: "54g"
shape: "Hybrid"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
