name: "Orbital Pathfinder LXR-222"
brand: "Orbital"
dimensions: "129.2 x 70 x 38mm"
weight: "55.5g"
shape: "Hybrid"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
