name: "Orbital Pathfinder CCH-000"
brand: "Orbital"
dimensions: "118 x 63 x 38mm"
weight: "54.4g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
