name: "PMM PULSE"
brand: "PMM"
dimensions: "119.2 x 60.8 x 37.2mm"
weight: "30g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wired"
buttons: "5"
