name: "PMM PULSE W"
brand: "PMM"
dimensions: "119.2 x 60.8 x 37.2mm"
weight: "37g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "4000Hz"
connection: "Wireless"
buttons: 5
