name: "Press Play Icarus V2 Mini"
brand: "Press Play"
dimensions: "116.5 x 61 x 38.5mm"
weight: "48g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
