name: "Press Play IRIS"
brand: "Press Play"
dimensions: "120.4 x 63.8 x 37.4mm"
weight: "52g"
shape: "Hybrid"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
