name: "Press Play Nova Ergo"
brand: "Press Play"
dimensions: "121 x 62.7 x 44mm"
weight: "52g"
shape: "Ergonomic"
sensor: "PixArt PAW3311"
dpiRange: "100-22000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
