name: "Press Play ATLAS"
brand: "Press Play"
dimensions: "123 x 66 x 43mm"
weight: "58g"
shape: "Ergonomic"
sensor: "PixArt PAW3311"
dpiRange: "100-12000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
