name: "Project W Opus"
brand: "Project W"
dimensions: "118.7 x 61.9 x 38.2mm"
weight: "38g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
