name: "Pulsar X2"
brand: "Pulsar"
weight: "52g"
shape: "Symmetrical"
sensor: "PAW3395"
dpiRange: "50-26000"
pollingRate: "4000Hz"
connection: "Wireless"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B0BS1DZ7JD?tag=prosettings-20"
