name: "Pulsar Xlite V3 Medium"
brand: "Pulsar"
weight: "52g"
shape: "Ergonomic"
sensor: "PAW3395"
dpiRange: "50-26000"
pollingRate: "4000Hz"
connection: "Wireless"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B0D75BPG4P?tag=prosettings-20"
