name: "Pulsar X2V2"
brand: "Pulsar"
weight: "52g"
shape: "Symmetrical"
dimensions: "120 x 63 x 38mm"
sensor: "PAW3395"
dpiRange: "50-26000"
pollingRate: "4000Hz"
buttons: 5
connection: "Wireless"
affiliateLink: "https://www.amazon.com/dp/B0BS1DZ7JD?tag=prosettings-20"
