name: "Rapoo VT1 Gen-2"
brand: "Rapoo"
dimensions: "119 x 62 x 38mm"
weight: "49g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
