name: "Rapoo VT1 Max Gen-2"
brand: "Rapoo"
dimensions: "119 x 62 x 38mm"
weight: "49g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
