name: "Razer DeathAdder V2 Mini"
brand: "Razer"
weight: "62g"
shape: "Ergonomic"
sensor: "PMW3359"
dpiRange: "200-8500"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 6
affiliateLink: "https://www.amazon.com/dp/B08FQMBYH5?tag=prosettings-20"
