name: "Razer DeathAdder V3"
brand: "Razer"
weight: "59g"
shape: "Ergonomic"
sensor: "Focus Pro 30K"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wired"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B0BNX3N8V8?tag=prosettings-20"
