name: "Razer DeathAdder V3 Pro"
brand: "Razer"
weight: "63g"
shape: "Ergonomic"
sensor: "Focus Pro 30K"
dpiRange: "100-30000"
pollingRate: "4000Hz"
connection: "Wireless"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B0B6LBFY8P?tag=prosettings-20"
