name: "Razer Viper 8KHz"
brand: "Razer"
weight: "71g"
shape: "Ambidextrous"
sensor: "Focus+"
dpiRange: "100-20000"
pollingRate: "8000Hz"
connection: "Wired"
buttons: 8
affiliateLink: "https://www.amazon.com/dp/B07TTC2MJG?tag=prosettings-20"
