name: "Redragon M725-LIT"
brand: "Redragon"
dimensions: "121 x 64 x 38mm"
weight: "49g"
shape: "Ambidextrous"
sensor: "SG 8925"
dpiRange: "100-8000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
