name: "Redragon M617 LIT"
brand: "Redragon"
dimensions: "120.8 x 64.3 x 37.9mm"
weight: "41g"
shape: "Ambidextrous"
sensor: "SG 8925"
dpiRange: "100-10000"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 5
