name: "Roccat Burst Pro Air"
brand: "Roccat"
weight: "81g"
shape: "Symmetrical"
dimensions: "120 x 58 x 38mm"
sensor: "Owl-Eye 19K"
dpiRange: "50-19000"
pollingRate: "1000Hz"
buttons: 6
connection: "Wireless"
