name: "Valkyrie VK M3 Pro"
brand: "Valkyrie"
dimensions: "118.5 x 62.5 x 37.8mm"
weight: "40g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
