name: "Valkyrie VK M3"
brand: "Valkyrie"
dimensions: "118.5 x 62.5 x 37.8mm"
weight: "40g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
