name: "VAXEE XE-S Wireless"
brand: "VAXEE"
dimensions: "118 x 59 x 37mm"
weight: "60g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "50-30000"
pollingRate: "4000Hz"
connection: "Wireless"
buttons: 5
