name: "VGN Dragonfly 3 Master+"
brand: "VGN"
dimensions: "125 x 63.3 x 40mm"
weight: "56g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
