name: "VGN Dragonfly King"
brand: "VGN"
dimensions: "119.4 x 59 x 38.3mm"
weight: "54g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-42000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
