name: "VGN Dragonfly F1 SE"
brand: "VGN"
dimensions: "121.2 x 63.8 x 37.6mm"
weight: "57g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-12000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
