name: "VGN Dragonfly 3 Pro Max"
brand: "VGN"
dimensions: "125 x 63.3 x 40mm"
weight: "58g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-36000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
