name: "Razer Viper V3 Pro"
brand: "Razer"
weight: "54g"
shape: "Ambidextrous"
dimensions: "127 x 64 x 40mm"
sensor: "Focus Pro 30K"
dpiRange: "100-35000"
pollingRate: "8000Hz"
buttons: 5
connection: "Wireless"
