name: "VortexSeries IGNIX F3 Pro"
brand: "VortexSeries"
dimensions: "118.5 x 61 x 39.7mm"
weight: "39g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395 Pro"
dpiRange: "100-40000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
