name: "VortexSeries IGNIX F7"
brand: "VortexSeries"
dimensions: "125.5 x 63 x 40mm"
weight: "55g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-24000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
