name: "VortexSeries IGNIX F1"
brand: "VortexSeries"
dimensions: "121.8 x 61.2 x 38mm"
weight: "53g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-24000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
