name: "VortexSeries IGNIX F5"
brand: "VortexSeries"
dimensions: "121 x 65 x 38mm"
weight: "49g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-24000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
