name: "VortexSeries IGNIX F7 Pro"
brand: "VortexSeries"
dimensions: "125.5 x 63 x 40mm"
weight: "55g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395 Pro"
dpiRange: "100-40000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
