name: "WLMOUSE Huan"
brand: "WLMOUSE"
dimensions: "116 x 61 x 38mm"
weight: "48g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950 HS"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
