name: "Wraith W1"
brand: "Wraith"
dimensions: "125 x 65 x 37mm"
weight: "56g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: 5
