name: "Xiaomi Wireless Mouse 3"
brand: "Xiaomi"
dimensions: "119 x 64 x 41mm"
weight: "57g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-12000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: 5
