name: "XIBERIA EX"
brand: "XIBERIA"
dimensions: "120 x 63 x 38mm"
weight: "45g"
shape: "Ambidextrous"
sensor: "PixArt PAW3950"
dpiRange: "100-30000"
pollingRate: "8000Hz"
connection: "Wireless"
buttons: "5"
