name: "Zaopin Z11 Pro"
brand: "Zaopin"
dimensions: "121.9 x 65 x 41.6mm"
weight: "55g"
shape: "Ambidextrous"
sensor: "PixArt PAW3395"
dpiRange: "100-26000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
