name: "Zaopin Z11"
brand: "Zaopin"
dimensions: "121.9 x 65 x 41.6mm"
weight: "55g"
shape: "Ambidextrous"
sensor: "PixArt PAW3311"
dpiRange: "100-12000"
pollingRate: "1000Hz"
connection: "Wireless"
buttons: "5"
