name: "Zaunkoenig M2K"
brand: "Zaunkoenig"
weight: "29g"
shape: "Symmetrical"
dimensions: "115 x 60 x 30mm"
sensor: "PAW3399"
dpiRange: "100-26000"
pollingRate: "8000Hz"
buttons: 3
connection: "Wired"
