name: "Zowie EC2-C"
brand: "Zowie"
weight: "73g"
shape: "Ergonomic"
sensor: "PMW3360"
dpiRange: "400-3200"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B09NLZMZH9?tag=prosettings-20"
