name: "Zowie EC2-B"
brand: "Zowie"
weight: "90g"
shape: "Ergonomic"
sensor: "PMW3360"
dpiRange: "400-3200"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B07H93NGB2?tag=prosettings-20"
