name: "Zowie S2-CW"
brand: "Zowie"
weight: "75g"
shape: "Symmetrical"
dimensions: "122 x 58 x 38mm"
sensor: "3370"
dpiRange: "400-3200"
pollingRate: "1000Hz"
buttons: 5
connection: "Wireless"
affiliateLink: "https://www.amazon.com/dp/B09NLZWJ8K?tag=prosettings-20"
