name: "Zowie ZA13-C"
brand: "Zowie"
weight: "65g"
shape: "Symmetrical"
sensor: "3360"
dpiRange: "400-3200"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 5
affiliateLink: "https://www.amazon.com/dp/B09NLZQ3VD?tag=prosettings-20"
