name: "Zowie FK2"
brand: "Zowie"
weight: "85g"
shape: "Ambidextrous"
sensor: "PMW3310"
dpiRange: "400-3200"
pollingRate: "1000Hz"
connection: "Wired"
buttons: 7
affiliateLink: "https://www.amazon.com/dp/B00WHRFMU0?tag=prosettings-20"
